# Generated by Django 4.2.9 on 2025-06-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean')], default='en', max_length=2)),
                ('strength', models.IntegerField(default=0)),
                ('p', models.FloatField(default=0.0)),
                ('last_seen', models.DateTimeField(default='1970-01-01T00:00:00Z')),
                ('synonyms', models.ManyToManyField(blank=True, to='words.word')),
            ],
            options={
                'ordering': ['word'],
                'unique_together': {('word', 'language')},
            },
        ),
    ]
