# Generated by Django 4.2.9 on 2025-06-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='synonyms',
            field=models.ManyToManyField(blank=True, through='words.Synonym', to='words.word'),
        ),
    ]
